//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Pharmacy_store_28_selfEntities : DbContext
{
    public Pharmacy_store_28_selfEntities()
        : base("name=Pharmacy_store_28_selfEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblBrand> tblBrands { get; set; }
    public virtual DbSet<tblCategory> tblCategories { get; set; }
    public virtual DbSet<tblProduct> tblProducts { get; set; }
    public virtual DbSet<tblUser> tblUsers { get; set; }

    public virtual int DeleteProduct(Nullable<int> productID)
    {
        var productIDParameter = productID.HasValue ?
            new ObjectParameter("ProductID", productID) :
            new ObjectParameter("ProductID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", productIDParameter);
    }

    public virtual ObjectResult<DoLogin_Result> DoLogin(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoLogin_Result>("DoLogin", emailParameter, passwordParameter);
    }

    public virtual ObjectResult<GetBrands_Result> GetBrands()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBrands_Result>("GetBrands");
    }

    public virtual ObjectResult<GetCategory_Result> GetCategory()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategory_Result>("GetCategory");
    }

    public virtual ObjectResult<GetProducts_Result> GetProducts()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts");
    }
}
